baseURL = 'https://ducnguyen96.github.io/'
languageCode = 'vi-vn'
theme = "cactus"
title = 'Thỉnh thoảng đôi lời'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/post"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[params]
logo = "https://avatars.githubusercontent.com/u/47471616?v=4"
[[params.social]]
  name = "github"
  link = "https://github.com/ducnguyen96"

[[params.social]]
  name = "email"
  link = "levinguyen.dl@gmail.com"
