baseURL = '/'
languageCode = 'vi-vn'
theme = "cactus"
title = 'Thỉnh thoảng đôi lời'
copyright = 'ducnguyen96'
disqusShortname = 'ducnguyen96'
paginate = 12
staticDir = ['static']
enableemoji = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "Projects"
# url = "/projects"
# weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 4

[params]
logo = "https://avatars.githubusercontent.com/u/47471616?v=4"
colortheme = "dark" # dark, light, white, or classic
rss = true
showAllPostsArchive = false
showAllPostsOnHomePage = true
description = "Là nơi chia sẻ lại những kiến thức, kinh nghiệm mình tiếp thu được trong quá trình học tập và làm việc. Và thỉnh thoảng cũng đăng một vài demo ngớ ngẩn nữa :smile:"
showProjectsList = true

[params.comments]
  enabled = true

[[params.social]]
  name = "github"
  link = "https://github.com/ducnguyen96"

[[params.social]]
  name = "email"
  link = "levinguyen.dl@gmail.com"

[[params.social]]
  name = "youtube"
  link = "https://www.youtube.com/channel/UCCrvmlNIXLgZOMAMn9VKBeA"