baseURL = '/'
languageCode = 'vi-vn'
theme = "cactus"
title = 'Thỉnh thoảng đôi lời'
copyright = 'ducnguyen96'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 3

[params]
logo = "https://avatars.githubusercontent.com/u/47471616?v=4"
colortheme = "dark" # dark, light, white, or classic

[[params.social]]
  name = "github"
  link = "https://github.com/ducnguyen96"

[[params.social]]
  name = "email"
  link = "levinguyen.dl@gmail.com"

[[params.social]]
  name = "youtube"
  link = "https://www.youtube.com/channel/UCCrvmlNIXLgZOMAMn9VKBeA"